name: Tools
description: Custom Tools Collection
author: StarTux
version: 0.1
main: com.winthier.tools.ToolsPlugin
depend: [ Custom, GenericEvents ]
commands:
  salesman:
    description: Salesman interface
    usage: |-
      /salesman reload
      /salesman open <shop> <player>
    permission: tools.salesman
permissions:
  tools.salesman:
    description: Use /salesman
